name: Run e2e tests

on:
  push:
    branches: ['develop', 'test-approach']
  repository_dispatch:
    branches: ['develop']
jobs:
  ping-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.10.0'
          registry-url: https://registry.npmjs.org/
      - name: 'Checkout the repository'
        uses: actions/checkout@v2

      - name: 'Install dependencies'
        run: npm install

#      - name: 'Running Login tests'
#        run: xvfb-run --auto-servernum npm run test:login

      - name: 'Running Other tests'
        run: xvfb-run --auto-servernum npm run test:without-login
