name: Run e2e tests

on:
  repository_dispatch:
    branches: ['develop']
jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.10.0'
          registry-url: https://registry.npmjs.org/
      - name: Install npm packages
        run: |
          npm install
      - name: Run tests
        run: npm run test

